databases:
  - name: flowerdb
    plan: free
    databaseName: flower
    user: flower

services:
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: true
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: SERPAPI_API_KEY
        sync: false
      - key: OPENAI_API_TYPE
        value: "azure"
      - key: OPENAI_API_VERSION
        value: "2023-07-01-preview"
      - key: OPENAI_API_BASE
        value: "https://faraday.openai.azure.com"
      - key: OPENAI_API_KEY
        sync: false
  - type: web
    name: app
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: flower
    region: ohio
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks flower --loglevel info"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flowerdb
          property: connectionString
      - key: FLOWER_BROKER_API # the flower docs say this is the env name, but the example uses CELERY_BROKER_URL... hmm?
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: FLOWER_PORT
        value: 10000
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
